### PR TITLE
Fix icon scroll behavior and overflow of modal

### LINKED ISSUE #1430: Design für Cesium-ion upload erstellen und implementieren
**Beschreibung**
Im Upload Tap können über den Button "Inhalte von Cesium ion hinzufügen" Inhalte von Cesium Ion hochgeladen werden.
für die jeweiligen Floating-Fenster (siehe nachfolgenden Screenshots) besteht derzeit noch kein Design. Dies soll in diesem Issues erstellt werden.

Image

Image

**ToDo**
- [ ] Design für die oben abgebildeten Floating-Fenster erstellen.

### PR DESCRIPTION
**Pull request by TIL-EBP**
closes #1430

### CODE REVIEW

File: ui/src/elements/ngm-ion-modal.ts [hunk 1]
```diff
@@ -322,11 +325,11 @@ export class NgmIonModal extends LitElementI18n {
       display: flex;
       justify-content: flex-end;
       gap: 16px;
-    }
-
-    // TODO: remove once the sgc-checkbox is updated
-    sgc-checkbox {
-      box-sizing: border-box;
```
Comment (daniel-va) [inline ui/src/elements/ngm-ion-modal.ts:329]: is this no longer needed?

**Review by daniel-va — APPROVED** [review]

File: ui/src/elements/ngm-ion-modal.ts (hunk 1 above)
Comment (TIL-EBP) [reply ui/src/elements/ngm-ion-modal.ts:329]: Nope
